# Generated by Django 5.1.4 on 2024-12-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
